#!/bin/sh
#----------------------------------------------------------------------------
#
#  Creator:     Ajay Chopra
#  Date:        03/05/2003
#
#  Copyright (c)  2003 by cisco Systems, Inc.
#  All rights reserved.
#
#  Wrapper for Java based CLI
#----------------------------------------------------------------------------

BASENAME=`basename $0`
FULLPATH=${CDETS_INSTALL_DIR:-/usr/cisco/packages/cdets/current}
#
# ppattnai: queue class is called if -Q switch is used with any write commands.
#
if [ $1 = '-Q' ]
then 
  CLASS=com.cisco.cdets.writequeue.queue
else
  #
  # eapenj: addcr and fixcr shares the same code ie java class file
  #
  if [ $BASENAME = 'addcr' ]
  then
    CLASS=com.cisco.cdetsng.bin.fixcr
  else
		if [ $BASENAME = 'addnote' ] || [ $BASENAME = 'addversions' ] || [ $BASENAME = 'fixcr' ] || [ $BASENAME = 'addfile' ]; then 
			CLASS=com.cisco.cdetsng.bin.${BASENAME}
		else
			CLASS=com.cisco.cdets.bin.${BASENAME}
		fi
	fi
fi
#echo $USER
if [ -z "$CDETS_USER" ]
then
CDETS_USER=$USER
fi
#echo $CDETS_USER
BINPATH=${FULLPATH}/bin
CLASSDIR=${FULLPATH}/classes
CLASSPATH="${CLASSDIR}:${CLASSDIR}/servlet-api-2.3.jar:${CLASSDIR}/activation.jar:${CLASSDIR}/javax.xml.stream-1.0.1.jar:${CLASSDIR}/jaxb-api-2.1.9.jar:${CLASSDIR}/jaxb-impl-2.1.9.jar:${CLASSDIR}/jaxb-xjc-2.1.9.jar:${CLASSDIR}/jersey-client-1.2.jar:${CLASSDIR}/jersey-core-1.2.jar:${CLASSDIR}/jsr311-api-1.1.1.jar:${CLASSDIR}/oauth-client-1.2.jar:${CLASSDIR}/oauth-signature-1.2.jar:${CLASSDIR}/json-simple-1.1.1.jar:${CLASSDIR}/printf.jar:${CLASSDIR}/Siebel.jar:${CLASSDIR}/SiebelJI_enu.jar:${CLASSDIR}/xalan.jar:${CLASSDIR}/xerces.jar:${CLASSDIR}/jargs.jar:${CLASSDIR}/h2-1.4.187.jar:${CLASSDIR}/mail.jar:${CLASSDIR}/activation.jar:${CLASSDIR}/ces_monitor.jar:${CLASSDIR}/activemq-all-5.4.3.jar:${CLASSDIR}/jersey-multipart-1.0.2.jar:${CLASSDIR}/mimepull.jar:${CLASSDIR}/vault-java-driver-5.1.0.jar"
CDETS_XSLT_PATH="${FULLPATH}/files/xslt/"
CDETS_ABOUT_PATH="${FULLPATH}/files/about/"

###### Source .cdetsrc if exists
if [ 'X'.$CDETS_BYPASS_RC = 'X.' ]; then
  if [ -r $HOME/.cdetsrc ]; then
    . $HOME/.cdetsrc
  fi
fi

CDETS_DEBUG=${CDETS_DEBUG:-false}
CDETS_DEFECTURL=${CDETS_DEFECTURL:-http://cdetsweb-prd.cisco.com/apps/cdets_defect}
#CDETS_WS_URL=${CDETS_WS_URL:-https://cdetsng.cisco.com/wsapi/latest-cli/findCRSimpleWrite/api}

if [ $BASENAME = 'addnote' ] || [ $BASENAME = 'addfile' ]; then 
 CDETS_URL=${CDETS_URL:-http://cdetsweb-prd.cisco.com/eaitws_enu/start.swe}
 CDETS_CONNECT_STRING=${CDETS_CONNECT_STRING:-siebel://cdetsapp-prd.cisco.com:2321/EScdetsprod/eaitwsobjmgr_enu}
else
 CDETS_URL=${CDETS_URL:-http://cdetsweb-prd.cisco.com/eai_enu/start.swe}
 CDETS_CONNECT_STRING=${CDETS_CONNECT_STRING:-siebel://cdetsapp-prd.cisco.com:2321/EScdetsprod/eaiobjmgr_enu}
fi

CDETS_TEXT_EXTENSION="txt text TXT TEXT htm html HTM HTML ${CDETS_TEXT_EXTENSION}"

# Use specific CDETS Java version if provided
CDETS_JAVA_HOME=${CDETS_JAVA_HOME:-X}
JAVACMD=$CDETS_JAVA_HOME/bin/java

if [ $CDETS_JAVA_HOME != 'X' ]; then
	if [ ! -x $JAVACMD ] ; then
		echo Invalid CDETS_JAVA_HOME: $CDETS_JAVA_HOME
	fi
fi

osName=`uname -s`
host=`hostname`
#echo $osName
if [ ! -x $JAVACMD ] ; then
	if [ $osName = 'SunOS' ]; then
 	   JAVACMD=/sw/licensed/sun/jdk/1.5.0_06/bin/java
	elif [ $osName = 'Linux' ]; then 
           #JAVACMD=/usr/bin/java
	   java_version=`/usr/bin/java -version 2>&1`
           version=`echo $java_version | cut -d"\"" -f2`
           if [[ $version < 1.5 ]]; then
             JAVACMD=/usr/cisco/bin/java
           else
             JAVACMD=/usr/bin/java
           fi
        else
           JAVACMD=/usr/cisco/bin/java	
        fi
# 	US31961 : harana : start	
	java_version=`$JAVACMD -version 2>&1`
    version=`echo $java_version | cut -d"\"" -f2`
	if [ $osName = 'SunOS' ]; then
# 		Default to JAVA_HOME if java version is less than 1.7 in std. path
    	JAVA_HOME=${JAVA_HOME:-X}
		if [ $JAVA_HOME != 'X' ]; then
			JAVACMD=$JAVA_HOME/bin/java
		fi
	else
		if [[ $version < 1.7 ]]; then
	# 		Default to JAVA_HOME if java version is less than 1.7 in std. path
			JAVA_HOME=${JAVA_HOME:-X}
			JAVACMD=$JAVA_HOME/bin/java
		fi
	fi
# 	US31961 : harana : end
	if [ ! -x $JAVACMD ] ; then
# 	Default to an older version
    	JAVACMD=/sw/licensed/sun/jdk/1.4.1_02/bin/java
	fi
	if [ ! -x $JAVACMD ] ; then
# 	Default to a latest version
    	JAVACMD=/usr/cisco/bin/java
	fi
	if [ ! -x $JAVACMD ] ; then
#       Default to a latest version
        JAVACMD=/usr/bin/java
        fi

	if [ ! -x $JAVACMD ] ; then
# Else. use JAVA_HOME if provided	
	 	JAVA_HOME=${JAVA_HOME:-X}
 		JAVACMD=$JAVA_HOME/bin/java
 	fi
			
	#TLS
	java_version=`$JAVACMD -version 2>&1`
    version=`echo $java_version | cut -d"\"" -f2`
	if [ $osName != 'SunOS' ]; then
		if [[ $version < 1.8 ]]; then
			#use default jre if java version is less than 1.7 in std. path
			JAVACMD=${FULLPATH}/jre/bin/java
			#echo Harana added this: $JAVACMD
		fi
	
	fi
# 	TLS : harana : end
fi

if [ ! -x $JAVACMD ] ; then
	echo Cannot locate compatible Java version!
	exit 1
fi

if [ $CDETS_DEBUG = 'true' ]; then
   JAVACMD="$JAVACMD -showversion"
fi

$JAVACMD \
-Daddfile.retry= \
-Duser.pwd="X" \
-Dlogin.retry=3 \
-Dlogin.sleep=3000 \
-Djava.net.preferIPv4Stack=true \
-Dcdets.basename=$BASENAME \
-Dcdets.os=$osName \
-Dcdets.hostname=$host \
-Dcdets.user=$CDETS_USER \
-Dcdets.aggAttSize=5242880 \
-Dfile.encoding="ISO8859_1" \
-Dcdets.xslt.path=$CDETS_XSLT_PATH \
-Dcdets.about.path=$CDETS_ABOUT_PATH \
-Dcdets.bin.path=$BINPATH \
-Dcdets.command="${BASENAME}" \
-Dcdets.url="${CDETS_URL}" \
-Dcdets.ws.url="${CDETS_WS_URL}" \
-Dconnect.string="${CDETS_CONNECT_STRING}" \
-Dcdets.debug="${CDETS_DEBUG}" \
-Dcdets.defecturl="${CDETS_DEFECTURL}" \
-Dcdets.text.extension="${CDETS_TEXT_EXTENSION}" \
-classpath $CLASSPATH \
-Xms156m \
-Xmx256m \
$CLASS \
"$@"
